### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by qubixes** [UtrechtUniversity/re-python-package#6]
In line with the re-python-package-poetry repo, this repo should be renamed `re-python-package-setuptools`.

**Comment by qubixes** [comment]
@jelletreep Do I have your permission?

**Comment by jelletreep** [comment]
Yes, @qubixes  sounds good

**Comment by qubixes** [comment]
@jelletreep Actually I am not an admin of this repository, so you'll have to do it.
